### ISSUE TITLE
[JOSS Review] Installation Instructions in tests wrong .yml file

### ISSUE THREAD

**Issue by gbouras13** [kdm9/Acanthophis#10]
Re https://github.com/openjournals/joss-reviews/issues/6062

I am running the example deployment of Acanthophis based on the Readme in the `tests` directory.

The instruction is 

`conda env create -f conda.yml -n acanthophis-demo`

but presumably the correct command should be 

`conda env create -f environment-setup.yml -n acanthophis-demo`

**Comment by kdm9** [comment]
Ooops, fixed, thanks @gbouras13
